services:
  ai_server:
    build: ./ai_server
    container_name: ai_server
    restart: always
    volumes:
      - /mnt/c/Users/thunder/Desktop/dev/Ai2차프로젝트/team-Gmaking/ai/runs/animal_cls_stage1/weights:/app/model_weights
    ports:
      - "8000:8000"
    networks:
      - gmaking-network

  growth_ai_server:
    build: ./growth_ai_server
    container_name: growth_ai_server
    restart: always
    volumes:
      - ./backend/gmaking/.env:/app/.env   
    working_dir: /app                      
    ports:
      - "8001:8001"
    depends_on:
      - db 
    networks:
      - gmaking-network                    

networks:
  gmaking-network: