services:
  db:
    image: mysql:8.4
    container_name: gmaking-mysql
    restart: always
    env_file:
      - ./.env
    ports:
      - "3307:3306"
    volumes:
      - ./db_init:/docker-entrypoint-initdb.d
    networks:
      - gmaking-network

  backend:
    build: ./backend/gmaking
    container_name: gmaking-backend
    restart: always
    environment:
      MODEL_SERVER_URL: "http://ai-server:8000"
      MODEL_SERVER_CLASSIFY_PATH: "/classify/image"
    env_file:
      - ./backend/gmaking/.env
    volumes:
      - ./backend/gmaking/src/main/resources/gcp-service-key.json:/app/src/main/resources/gcp-service-key.json
    ports:
      - "8080:8080"
    depends_on:
      - db
      - ai-server
      - growth-ai-server
    networks:
      - gmaking-network

  frontend:
    build: ./frontend
    container_name: gmaking-frontend
    restart: always
    env_file:
      - ./frontend/.env
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - gmaking-network

  ai-server:
    build: ./ai_server
    container_name: ai-server
    restart: always
    ports:
      - "8000:8000"
    networks:
      - gmaking-network

  growth-ai-server:
    build: ./growth_ai_server
    container_name: growth-ai-server
    restart: always
    env_file:
      - ./backend/gmaking/.env
    working_dir: /app
    ports:
      - "8001:8001"
    depends_on:
      - db
    networks:
      - gmaking-network

networks:
  gmaking-network:
    driver: bridge
